import type { Dataset } from '@/lib/domain/types'

const lit = (value: unknown): string => {
  if (value === null || value === undefined || value === '') return 'null'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  return `'${String(value).replace(/'/g, "''")}'`
}

export function insert(table: string, columns: string[], rows: unknown[][], batch = 400): string {
  const out: string[] = []
  for (let i = 0; i < rows.length; i += batch) {
    const values = rows.slice(i, i + batch).map((row) => `  (${row.map(lit).join(', ')})`).join(',\n')
    out.push(`insert into public.${table} (${columns.join(', ')}) values\n${values};`)
  }
  return out.join('\n\n')
}

const firstOfMonth = (period: string) => `${period}-01`

/** The stored (non-derived) tables as one idempotent SQL script. */
export function datasetToSql(d: Dataset): string {
  return [
    '-- SkillPulse pilot seed. PROTOTYPE SYNTHETIC DATA — not official statistics.',
    '-- Generated by `pnpm data:ingest` from data/pilot/raw. Do not edit by hand.',
    'begin;',
    'truncate public.gap_analysis, public.supply_forecasts, public.demand_forecasts, public.labour_demand, public.training_capacity, public.training_centres, public.data_sources, public.dataset_meta restart identity;',
    'delete from public.trades; delete from public.sectors; delete from public.districts; delete from public.states;',
    insert('dataset_meta', ['label', 'synthetic', 'as_of_period', 'updated_at', 'current_training_year'], [[d.meta.label, d.meta.synthetic, firstOfMonth(d.meta.asOfPeriod), d.meta.updatedAt, d.meta.currentTrainingYear]]),
    insert('states', ['id', 'name', 'name_hi', 'code'], d.states.map((s) => [s.id, s.name, s.nameHi, s.code])),
    insert('districts', ['id', 'state_id', 'name', 'name_hi', 'code'], d.districts.map((x) => [x.id, x.stateId, x.name, x.nameHi, x.code])),
    insert('sectors', ['id', 'name', 'name_hi', 'code'], d.sectors.map((s) => [s.id, s.name, s.nameHi, s.code])),
    insert('trades', ['id', 'sector_id', 'name', 'name_hi', 'nco_code', 'nsqf_level'], d.trades.map((t) => [t.id, t.sectorId, t.name, t.nameHi, t.ncoCode, t.nsqfLevel])),
    insert('training_centres', ['id', 'name', 'district_id', 'sector_id', 'status', 'capacity'], d.trainingCentres.map((c) => [c.id, c.name, c.districtId, c.sectorId, c.status, c.capacity])),
    insert('data_sources', ['id', 'name', 'description', 'source_type', 'last_updated', 'status', 'coverage', 'granularity', 'feeds', 'records_in', 'records_mapped'],
      d.dataSources.map((s) => [s.id, s.name, s.description, s.sourceType, s.lastUpdated, s.status, s.coverage, s.granularity, s.feeds, s.recordsIn, s.recordsMapped])),
    insert('training_capacity', ['district_id', 'sector_id', 'trade_id', 'year', 'allocated_seats', 'enrolled', 'completed', 'placed'],
      d.trainingCapacity.map((r) => [r.districtId, r.sectorId, r.tradeId, r.year, r.allocatedSeats, r.enrolled, r.completed, r.placed])),
    insert('labour_demand', ['district_id', 'sector_id', 'trade_id', 'period', 'job_postings', 'hiring_signal', 'employment_registrations', 'industry_demand_signal', 'source'],
      d.labourDemand.map((r) => [r.districtId, r.sectorId, r.tradeId, firstOfMonth(r.period), r.jobPostings, r.hiringSignal, r.employmentRegistrations, r.industryDemandSignal, r.source])),
    'commit;',
    '',
  ].join('\n\n')
}
